version: '3.8'

services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
      args:
        - NODE_ENV=${NODE_ENV}
    ports:
      - "3000:80"
    environment:
      - NODE_ENV=${NODE_ENV}
    volumes:
      - ./client:/app
      - /app/node_modules
#    user: "1000:1000"
    depends_on:
      - server

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
      args:
        - NODE_ENV=${NODE_ENV}
    ports:
      - "5000:5000"
    volumes:
      - ./server:/app
      - /app/node_modules
    user: "1000:1000"
#    environment:
#      - MONGO_URI=${MONGO_URI}
#      - NODE_ENV=${NODE_ENV}
