version: '3.8'

services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
      target: ${NODE_ENV:-dev}_stage
      args:
        - NODE_ENV=${NODE_ENV:-dev}
    ports:
      - "3000:80"
    env_file:
      - ./client/.env.${NODE_ENV:-dev}
    volumes:
      - ./client:/app
      - /app/node_modules
    depends_on:
      - server

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
      args:
        - NODE_ENV=${NODE_ENV:-dev}
    ports:
      - "5000:5000"
    volumes:
      - ./server:/app
      - /app/node_modules
    env_file:
      - ./server/.env.${NODE_ENV:-dev}
    user: "1000:1000"
