version: '3.8'

services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./client:/app
      - /app/node_modules
    user: "${UID}:${GID}"  # Run container as the host user
    environment:
        - UID=${UID}
        - GID=${GID}
    depends_on:
      - server
#    command: npm start

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./server:/app
      - /app/node_modules
    user: "${UID}:${GID}"  # Run container as the host user
    environment:
      - MONGO_URI=mongodb+srv://mlandman:meni8633@cluster0.ws6nf.mongodb.net/books?retryWrites=true&w=majority&appName=Cluster0
      - UID=${UID}
      - GID=${GID}
#    command: npx nodemon server.js
